name: flutter_docig_venda
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  path_provider: ^2.1.2
  http: ^0.13.6
 
  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  sqflite: ^2.4.2
  connectivity_plus: ^6.1.3
  share_plus: ^10.1.4
  flutter_pdfview: 1.3.2
  device_info_plus: ^11.3.3
  intl: ^0.20.2
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/MobileDousig.png
    - assets/MobileDousigSemfundo.png
    - assets/MobileDousigFundoBranco.png

flutter_launcher_name:
  name: "MobileDuosig"
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/MobileDousigFundoBranco.png"
  adaptive_icon_background: "#ffffff" # (Para Android)
  adaptive_icon_foreground: "assets/MobileDousigFundoBranco.png" # (Para Android)



